### PR TITLE
changes in find_pairs

### PR DESCRIPTION
**Pull request by sneha-matrix**
genes.list is now null , added test for that too

### CODE REVIEW

**Comment by sneha-matrix** [comment]
formatting changes 120 character per line

**Comment by sneha-matrix** [comment]
formatting changes 120 character per line

**Comment by huipan1973** [comment]
update

**Comment by sneha-matrix** [comment]
> update

sorry i didn’t get you.

**Comment by huipan1973** [comment]
Thanks!

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 27, 2020 at 11:52 AM, sneha-matrix<notifications@github.com> wrote:   

update


sorry i didn’t get you.

**Pull request merged**
